import dimStarFilled from "../assets/Icons/dimStarFilled.png";
import dimStarHalffilled from "../assets/Icons/dimStarHalffilled.png";
import dimStarOutlined from "../assets/Icons/dimStarOutlined.png";
import imgBecoming from "../assets/Icons/imgBecoming.png";
import imgMaster from "../assets/Icons/imgMaster.png";
import imgSentimentAnalysis from "../assets/Icons/imgSentimentAnalysis.png";
import imgTimemanagement from "../assets/Icons/imgTimemanagement.png";
import bestsellerLabel from "../assets/Icons/bestsellerLabel.png";

export const tabsEnglish = [
  {
    name: "All Categories",
    courses: [
      {
        courseTitle: "Mastering Effective Communication Skills",
        reviews: "244 reviews",
        rating: 4.8,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp320,000",
        discountedPrice: "Rp150,000",
        videos: 24,
        duration: "8.5h",
        discount: "30%",
        tag: bestsellerLabel,
        profileImage: imgMaster,
      },
      {
        courseTitle: "Becoming a Power Negotiator: Win-Win Strategies",
        reviews: "425 reviews",
        rating: 4.2,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp250,000",
        discountedPrice: "Rp100,000",
        videos: 6,
        duration: "4h",
        discount: "30%",
        profileImage: imgBecoming,
      },
      {
        courseTitle: "Time Management Techniques for Maximum Productivity",
        reviews: "227 reviews",
        rating: 4.7,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp550,000",
        discountedPrice: "Rp250,000",
        videos: 8,
        duration: "1.5h",
        discount: "30%",
        tag: bestsellerLabel,
        profileImage: imgTimemanagement,
      },
      {
        courseTitle: "Sentiment Analysis with Deep Learning using BERT",
        reviews: "25 reviews",
        rating: 4.9,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp400,000",
        discountedPrice: "Rp120,000",
        videos: 32,
        duration: "12.5h",
        discount: "30%",
        tag: bestsellerLabel,
        profileImage: imgSentimentAnalysis,
      },
    ],
  },
  {
    name: "Development",
    courses: [
      {
        courseTitle: "Mastering Effective Communication Skills",
        reviews: "244 reviews",
        rating: 4.8,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp320,000",
        discountedPrice: "Rp150,000",
        videos: 24,
        duration: "8.5h",
        discount: "30%",
        tag: bestsellerLabel,
        profileImage: imgMaster,
      },
      {
        courseTitle: "Becoming a Power Negotiator: Win-Win Strategies",
        reviews: "425 reviews",
        rating: 4.2,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp250,000",
        discountedPrice: "Rp100,000",
        videos: 6,
        duration: "4h",
        discount: "30%",
        profileImage: imgBecoming,
      },
      {
        courseTitle: "Time Management Techniques for Maximum Productivity",
        reviews: "227 reviews",
        rating: 4.7,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp550,000",
        discountedPrice: "Rp250,000",
        videos: 8,
        duration: "1.5h",
        discount: "30%",
        tag: bestsellerLabel,
        profileImage: imgTimemanagement,
      },
      {
        courseTitle: "Sentiment Analysis with Deep Learning using BERT",
        reviews: "25 reviews",
        rating: 4.9,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp400,000",
        discountedPrice: "Rp120,000",
        videos: 32,
        duration: "12.5h",
        discount: "30%",
        tag: bestsellerLabel,
        profileImage: imgSentimentAnalysis,
      },
    ],
  },
  {
    name: "IT & Software",
    courses: [
      {
        courseTitle: "Mastering Effective Communication Skills",
        reviews: "244 reviews",
        rating: 4.8,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp320,000",
        discountedPrice: "Rp150,000",
        videos: 24,
        duration: "8.5h",
        discount: "30%",
        tag: bestsellerLabel,
        profileImage: imgMaster,
      },
      {
        courseTitle: "Becoming a Power Negotiator: Win-Win Strategies",
        reviews: "425 reviews",
        rating: 4.2,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp250,000",
        discountedPrice: "Rp100,000",
        videos: 6,
        duration: "4h",
        discount: "30%",
        profileImage: imgBecoming,
      },
      {
        courseTitle: "Time Management Techniques for Maximum Productivity",
        reviews: "227 reviews",
        rating: 4.7,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp550,000",
        discountedPrice: "Rp250,000",
        videos: 8,
        duration: "1.5h",
        discount: "30%",
        tag: bestsellerLabel,
        profileImage: imgTimemanagement,
      },
      {
        courseTitle: "Sentiment Analysis with Deep Learning using BERT",
        reviews: "25 reviews",
        rating: 4.9,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp400,000",
        discountedPrice: "Rp120,000",
        videos: 32,
        duration: "12.5h",
        discount: "30%",
        tag: bestsellerLabel,
        profileImage: imgSentimentAnalysis,
      },
    ],
  },
  {
    name: "Design",
    courses: [
      {
        courseTitle: "Mastering Effective Communication Skills",
        reviews: "244 reviews",
        rating: 4.8,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp320,000",
        discountedPrice: "Rp150,000",
        videos: 24,
        duration: "8.5h",
        discount: "30%",
        tag: bestsellerLabel,
        profileImage: imgMaster,
      },
      {
        courseTitle: "Becoming a Power Negotiator: Win-Win Strategies",
        reviews: "425 reviews",
        rating: 4.2,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp250,000",
        discountedPrice: "Rp100,000",
        videos: 6,
        duration: "4h",
        discount: "30%",
        profileImage: imgBecoming,
      },
      {
        courseTitle: "Time Management Techniques for Maximum Productivity",
        reviews: "227 reviews",
        rating: 4.7,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp550,000",
        discountedPrice: "Rp250,000",
        videos: 8,
        duration: "1.5h",
        discount: "30%",
        tag: bestsellerLabel,
        profileImage: imgTimemanagement,
      },
      {
        courseTitle: "Sentiment Analysis with Deep Learning using BERT",
        reviews: "25 reviews",
        rating: 4.9,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp400,000",
        discountedPrice: "Rp120,000",
        videos: 32,
        duration: "12.5h",
        discount: "30%",
        tag: bestsellerLabel,
        profileImage: imgSentimentAnalysis,
      },
    ],
  },
  {
    name: "Business",
    courses: [
      {
        courseTitle: "Mastering Effective Communication Skills",
        reviews: "244 reviews",
        rating: 4.8,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp320,000",
        discountedPrice: "Rp150,000",
        videos: 24,
        duration: "8.5h",
        discount: "30%",
        tag: bestsellerLabel,
        profileImage: imgMaster,
      },
      {
        courseTitle: "Becoming a Power Negotiator: Win-Win Strategies",
        reviews: "425 reviews",
        rating: 4.2,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp250,000",
        discountedPrice: "Rp100,000",
        videos: 6,
        duration: "4h",
        discount: "30%",
        profileImage: imgBecoming,
      },
      {
        courseTitle: "Time Management Techniques for Maximum Productivity",
        reviews: "227 reviews",
        rating: 4.7,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp550,000",
        discountedPrice: "Rp250,000",
        videos: 8,
        duration: "1.5h",
        discount: "30%",
        tag: bestsellerLabel,
        profileImage: imgTimemanagement,
      },
      {
        courseTitle: "Sentiment Analysis with Deep Learning using BERT",
        reviews: "25 reviews",
        rating: 4.9,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp400,000",
        discountedPrice: "Rp120,000",
        videos: 32,
        duration: "12.5h",
        discount: "30%",
        tag: bestsellerLabel,
        profileImage: imgSentimentAnalysis,
      },
    ],
  },
  {
    name: "Lifestyle",
    courses: [
      {
        courseTitle: "Mastering Effective Communication Skills",
        reviews: "244 reviews",
        rating: 4.8,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp320,000",
        discountedPrice: "Rp150,000",
        videos: 24,
        duration: "8.5h",
        discount: "30%",
        tag: bestsellerLabel,
        profileImage: imgMaster,
      },
      {
        courseTitle: "Becoming a Power Negotiator: Win-Win Strategies",
        reviews: "425 reviews",
        rating: 4.2,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp250,000",
        discountedPrice: "Rp100,000",
        videos: 6,
        duration: "4h",
        discount: "30%",
        profileImage: imgBecoming,
      },
      {
        courseTitle: "Time Management Techniques for Maximum Productivity",
        reviews: "227 reviews",
        rating: 4.7,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp550,000",
        discountedPrice: "Rp250,000",
        videos: 8,
        duration: "1.5h",
        discount: "30%",
        tag: bestsellerLabel,
        profileImage: imgTimemanagement,
      },
      {
        courseTitle: "Sentiment Analysis with Deep Learning using BERT",
        reviews: "25 reviews",
        rating: 4.9,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp400,000",
        discountedPrice: "Rp120,000",
        videos: 32,
        duration: "12.5h",
        discount: "30%",
        tag: bestsellerLabel,
        profileImage: imgSentimentAnalysis,
      },
    ],
  },
  {
    name: "Marketing",
    courses: [
      {
        courseTitle: "Mastering Effective Communication Skills",
        reviews: "244 reviews",
        rating: 4.8,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp320,000",
        discountedPrice: "Rp150,000",
        videos: 24,
        duration: "8.5h",
        discount: "30%",
        tag: bestsellerLabel,
        profileImage: imgMaster,
      },
      {
        courseTitle: "Becoming a Power Negotiator: Win-Win Strategies",
        reviews: "425 reviews",
        rating: 4.2,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp250,000",
        discountedPrice: "Rp100,000",
        videos: 6,
        duration: "4h",
        discount: "30%",
        profileImage: imgBecoming,
      },
      {
        courseTitle: "Time Management Techniques for Maximum Productivity",
        reviews: "227 reviews",
        rating: 4.7,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp550,000",
        discountedPrice: "Rp250,000",
        videos: 8,
        duration: "1.5h",
        discount: "30%",
        tag: bestsellerLabel,
        profileImage: imgTimemanagement,
      },
      {
        courseTitle: "Sentiment Analysis with Deep Learning using BERT",
        reviews: "25 reviews",
        rating: 4.9,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp400,000",
        discountedPrice: "Rp120,000",
        videos: 32,
        duration: "12.5h",
        discount: "30%",
        tag: bestsellerLabel,
        profileImage: imgSentimentAnalysis,
      },
    ],
  },
];
