import bestsellerPersian from "../../assets/Icons/bestsellerPersian.png";
import dimStarFilled from "../../assets/Icons/dimStarFilled.png";
import dimStarHalffilled from "../../assets/Icons/dimStarHalffilled.png";
import dimStarOutlined from "../../assets/Icons/dimStarOutlined.png";
import imgBecoming from "../../assets/Icons/imgBecoming.png";
import imgMaster from "../../assets/Icons/imgMaster.png";
import imgSentimentAnalysis from "../../assets/Icons/imgSentimentAnalysis.png";
import imgTimemanagement from "../../assets/Icons/imgTimemanagement.png";

export const tabsPersian = [
  {
    name: "همه دسته ها",
    courses: [
      {
        courseTitle: "تسلط بر مهارت های ارتباط موثر",
        reviews: "244 بررسی ها",
        rating: 4.8,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp320,000",
        discountedPrice: "Rp150,000",
        videos: 24,
        duration: "8.5h",
        discount: "30%",
        tag: bestsellerPersian,
        profileImage: imgMaster,
      },
      {
        courseTitle:
          "تبدیل شدن به یک مذاکره کننده قدرتمند: استراتژی های برد-برد",
        reviews: "425 بررسی ها",
        rating: 4.2,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp250,000",
        discountedPrice: "Rp100,000",
        videos: 6,
        duration: "4h",
        discount: "30%",
        profileImage: imgBecoming,
      },
      {
        courseTitle: "تکنیک های مدیریت زمان برای حداکثر بهره وری",
        reviews: "227 بررسی ها",
        rating: 4.7,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp550,000",
        discountedPrice: "Rp250,000",
        videos: 8,
        duration: "1.5h",
        discount: "30%",
        tag: bestsellerPersian,
        profileImage: imgTimemanagement,
      },
      {
        courseTitle: "تجزیه و تحلیل احساسات با یادگیری عمیق با استفاده از BERT",
        reviews: "25 بررسی ها",
        rating: 4.9,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp400,000",
        discountedPrice: "Rp120,000",
        videos: 32,
        duration: "12.5h",
        discount: "30%",
        tag: bestsellerPersian,
        profileImage: imgSentimentAnalysis,
      },
    ],
  },
  {
    name: "بازاریابی",
    courses: [
      {
        courseTitle: "تسلط بر مهارت های ارتباط موثر",
        reviews: "244 بررسی ها",
        rating: 4.8,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp320,000",
        discountedPrice: "Rp150,000",
        videos: 24,
        duration: "8.5h",
        discount: "30%",
        tag: bestsellerPersian,
        profileImage: imgMaster,
      },
      {
        courseTitle:
          "تبدیل شدن به یک مذاکره کننده قدرتمند: استراتژی های برد-برد",
        reviews: "425 بررسی ها",
        rating: 4.2,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp250,000",
        discountedPrice: "Rp100,000",
        videos: 6,
        duration: "4h",
        discount: "30%",
        profileImage: imgBecoming,
      },
      {
        courseTitle: "تکنیک های مدیریت زمان برای حداکثر بهره وری",
        reviews: "227 بررسی ها",
        rating: 4.7,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp550,000",
        discountedPrice: "Rp250,000",
        videos: 8,
        duration: "1.5h",
        discount: "30%",
        tag: bestsellerPersian,
        profileImage: imgTimemanagement,
      },
      {
        courseTitle: "تجزیه و تحلیل احساسات با یادگیری عمیق با استفاده از BERT",
        reviews: "25 بررسی ها",
        rating: 4.9,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp400,000",
        discountedPrice: "Rp120,000",
        videos: 32,
        duration: "12.5h",
        discount: "30%",
        tag: bestsellerPersian,
        profileImage: imgSentimentAnalysis,
      },
    ],
  },

  {
    name: "سبک زندگی",
    courses: [
      {
        courseTitle: "تسلط بر مهارت های ارتباط موثر",
        reviews: "244 بررسی ها",
        rating: 4.8,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp320,000",
        discountedPrice: "Rp150,000",
        videos: 24,
        duration: "8.5h",
        discount: "30%",
        tag: bestsellerPersian,
        profileImage: imgMaster,
      },
      {
        courseTitle:
          "تبدیل شدن به یک مذاکره کننده قدرتمند: استراتژی های برد-برد",
        reviews: "425 بررسی ها",
        rating: 4.2,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp250,000",
        discountedPrice: "Rp100,000",
        videos: 6,
        duration: "4h",
        discount: "30%",
        profileImage: imgBecoming,
      },
      {
        courseTitle: "تکنیک های مدیریت زمان برای حداکثر بهره وری",
        reviews: "227 بررسی ها",
        rating: 4.7,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp550,000",
        discountedPrice: "Rp250,000",
        videos: 8,
        duration: "1.5h",
        discount: "30%",
        tag: bestsellerPersian,
        profileImage: imgTimemanagement,
      },
      {
        courseTitle: "تجزیه و تحلیل احساسات با یادگیری عمیق با استفاده از BERT",
        reviews: "25 بررسی ها",
        rating: 4.9,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp400,000",
        discountedPrice: "Rp120,000",
        videos: 32,
        duration: "12.5h",
        discount: "30%",
        tag: bestsellerPersian,
        profileImage: imgSentimentAnalysis,
      },
    ],
  },

  {
    name: "تجارت",
    courses: [
      {
        courseTitle: "تسلط بر مهارت های ارتباط موثر",
        reviews: "244 بررسی ها",
        rating: 4.8,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp320,000",
        discountedPrice: "Rp150,000",
        videos: 24,
        duration: "8.5h",
        discount: "30%",
        tag: bestsellerPersian,
        profileImage: imgMaster,
      },
      {
        courseTitle:
          "تبدیل شدن به یک مذاکره کننده قدرتمند: استراتژی های برد-برد",
        reviews: "425 بررسی ها",
        rating: 4.2,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp250,000",
        discountedPrice: "Rp100,000",
        videos: 6,
        duration: "4h",
        discount: "30%",
        profileImage: imgBecoming,
      },
      {
        courseTitle: "تکنیک های مدیریت زمان برای حداکثر بهره وری",
        reviews: "227 بررسی ها",
        rating: 4.7,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp550,000",
        discountedPrice: "Rp250,000",
        videos: 8,
        duration: "1.5h",
        discount: "30%",
        tag: bestsellerPersian,
        profileImage: imgTimemanagement,
      },
      {
        courseTitle: "تجزیه و تحلیل احساسات با یادگیری عمیق با استفاده از BERT",
        reviews: "25 بررسی ها",
        rating: 4.9,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp400,000",
        discountedPrice: "Rp120,000",
        videos: 32,
        duration: "12.5h",
        discount: "30%",
        tag: bestsellerPersian,
        profileImage: imgSentimentAnalysis,
      },
    ],
  },

  {
    name: "طراحی",
    courses: [
      {
        courseTitle: "تسلط بر مهارت های ارتباط موثر",
        reviews: "244 بررسی ها",
        rating: 4.8,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp320,000",
        discountedPrice: "Rp150,000",
        videos: 24,
        duration: "8.5h",
        discount: "30%",
        tag: bestsellerPersian,
        profileImage: imgMaster,
      },
      {
        courseTitle:
          "تبدیل شدن به یک مذاکره کننده قدرتمند: استراتژی های برد-برد",
        reviews: "425 بررسی ها",
        rating: 4.2,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp250,000",
        discountedPrice: "Rp100,000",
        videos: 6,
        duration: "4h",
        discount: "30%",
        profileImage: imgBecoming,
      },
      {
        courseTitle: "تکنیک های مدیریت زمان برای حداکثر بهره وری",
        reviews: "227 بررسی ها",
        rating: 4.7,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp550,000",
        discountedPrice: "Rp250,000",
        videos: 8,
        duration: "1.5h",
        discount: "30%",
        tag: bestsellerPersian,
        profileImage: imgTimemanagement,
      },
      {
        courseTitle: "تجزیه و تحلیل احساسات با یادگیری عمیق با استفاده از BERT",
        reviews: "25 بررسی ها",
        rating: 4.9,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp400,000",
        discountedPrice: "Rp120,000",
        videos: 32,
        duration: "12.5h",
        discount: "30%",
        tag: bestsellerPersian,
        profileImage: imgSentimentAnalysis,
      },
    ],
  },

  {
    name: "فناوری اطلاعات و نرم افزار",
    courses: [
      {
        courseTitle: "تسلط بر مهارت های ارتباط موثر",
        reviews: "244 بررسی ها",
        rating: 4.8,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp320,000",
        discountedPrice: "Rp150,000",
        videos: 24,
        duration: "8.5h",
        discount: "30%",
        tag: bestsellerPersian,
        profileImage: imgMaster,
      },
      {
        courseTitle:
          "تبدیل شدن به یک مذاکره کننده قدرتمند: استراتژی های برد-برد",
        reviews: "425 بررسی ها",
        rating: 4.2,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp250,000",
        discountedPrice: "Rp100,000",
        videos: 6,
        duration: "4h",
        discount: "30%",
        profileImage: imgBecoming,
      },
      {
        courseTitle: "تکنیک های مدیریت زمان برای حداکثر بهره وری",
        reviews: "227 بررسی ها",
        rating: 4.7,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp550,000",
        discountedPrice: "Rp250,000",
        videos: 8,
        duration: "1.5h",
        discount: "30%",
        tag: bestsellerPersian,
        profileImage: imgTimemanagement,
      },
      {
        courseTitle: "تجزیه و تحلیل احساسات با یادگیری عمیق با استفاده از BERT",
        reviews: "25 بررسی ها",
        rating: 4.9,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp400,000",
        discountedPrice: "Rp120,000",
        videos: 32,
        duration: "12.5h",
        discount: "30%",
        tag: bestsellerPersian,
        profileImage: imgSentimentAnalysis,
      },
    ],
  },

  {
    name: "توسعه",
    courses: [
      {
        courseTitle: "تسلط بر مهارت های ارتباط موثر",
        reviews: "244 بررسی ها",
        rating: 4.8,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp320,000",
        discountedPrice: "Rp150,000",
        videos: 24,
        duration: "8.5h",
        discount: "30%",
        tag: bestsellerPersian,
        profileImage: imgMaster,
      },
      {
        courseTitle:
          "تبدیل شدن به یک مذاکره کننده قدرتمند: استراتژی های برد-برد",
        reviews: "425 بررسی ها",
        rating: 4.2,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarOutlined,
        ],
        originalPrice: "Rp250,000",
        discountedPrice: "Rp100,000",
        videos: 6,
        duration: "4h",
        discount: "30%",
        profileImage: imgBecoming,
      },
      {
        courseTitle: "تکنیک های مدیریت زمان برای حداکثر بهره وری",
        reviews: "227 بررسی ها",
        rating: 4.7,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp550,000",
        discountedPrice: "Rp250,000",
        videos: 8,
        duration: "1.5h",
        discount: "30%",
        tag: bestsellerPersian,
        profileImage: imgTimemanagement,
      },
      {
        courseTitle: "تجزیه و تحلیل احساسات با یادگیری عمیق با استفاده از BERT",
        reviews: "25 بررسی ها",
        rating: 4.9,
        rateStar: [
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarFilled,
          dimStarHalffilled,
        ],
        originalPrice: "Rp400,000",
        discountedPrice: "Rp120,000",
        videos: 32,
        duration: "12.5h",
        discount: "30%",
        tag: bestsellerPersian,
        profileImage: imgSentimentAnalysis,
      },
    ],
  },
];
